parameters:
#

services:

    info.forum:
      class: Putr\Cli\InfoDisseminationBundle\Service\VanillaForumComments
      arguments: [%info_dissemination.forum.url%, @logger, @service_container, %info_dissemination.timeInterval%]
      tags:
            - { name: monolog.logger, channel: forumService }

    info.mediawiki:
      class: Putr\Cli\InfoDisseminationBundle\Service\MediaWikiChanges
      arguments: [%info_dissemination.wiki.url%, @logger, @service_container, %info_dissemination.timeInterval%]
      tags:
            - { name: monolog.logger, channel: mediawikiService }

    info.wordpress:
      class: Putr\Cli\InfoDisseminationBundle\Service\WordpressUpdates
      arguments: [%info_dissemination.wp.url%, @logger, @service_container, %info_dissemination.timeInterval%]
      tags:
            - { name: monolog.logger, channel: wordpressService }